# -*- coding: utf-8 -*-
"""Assignment 3 python - mathan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XagMzAFeq0rWo25PsPR9pjYfhEyLBgFw
"""

# importing random function
import random

# generating randum number between 1 to 10

secret_number = random.randint(1, 10)

attempts = 3

print("Welcome to the number guessing game!")

while attempts > 0:
  guess = int(input("Guess the number(Between 1 and 10): "))

  if guess < 0 or guess > 10:
    print("Your guess is out of range. please guess a number betwen 1 and 10.")
    continue

  if guess > secret_number:
    print("Too high. try again.")

  if guess < secret_number:
    print("Too low. try again.")

  else:
    print("Congratulations! you guessed the correct number.")
    break

  attempts -= 1
  print ("Attempts left: ", attempts)

else:
  print("Better luck next time! you ran out of attempts.")

# for loop - table multiplication
number = int(input("Enter the number for which you want to multiplication table: "))
for i in range(1, 11):
  print(number, "x", i, "=", number *i)

# function - calculating bmi value
def calculate_bmi(weight, height):
  bmi = weight / (height ** 2)
  return bmi
weight = float(input("Enter your weight in kg: "))
height = float(input("Enter your height in meters: "))
Bmi_value = calculate_bmi(weight, height)
print("Your BMI is: ", round(Bmi_value, 2))