# -*- coding: utf-8 -*-
"""Assignment 2 python - mathan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X4FD7y3BS26Di2FpSRjdvcCngZnl71c5
"""

# creating list
age_list = [24, 25, 26, 27, 28]
name_list = ["arun", "kumar", "raj", "karthik", "ram"]

print("Age list: ", age_list)
print("Name list: ", name_list)

# append
name_list.append("Yazhini")
print(name_list)

# inserting element at 2nd position
age_list.insert(2,30)
print(age_list)

# removing element in a string
name_list.remove("Yazhini")
print(name_list)

# removing last element using pop function
popped_element = age_list.pop()
print(popped_element)

# extending age list
age_list.extend([29, 30, 26])
print(age_list)

# shorting
age_list.sort(reverse= True)
print(age_list)

# max, min, total age values
print("maximum age:", max(age_list))
print("minimum age:", min(age_list))
print("total age:", sum(age_list))

# printing element
print(name_list[0])
print(name_list[-1])
print(name_list[2:4])
print(name_list[::-1])

# creating dictionary
student_marks = {"arun": 52, "kumar": 85, "ram": 70, "karthik": 68, "yuvi": 40}
print(student_marks)

# printing specific value
print(student_marks["ram"])

#adding new student value
student_marks["Janani"] = 80
print(student_marks)

# updating existing value
student_marks["kumar"] = 82
print(student_marks)

# printing values with key, values, items
print(student_marks.keys())
print(student_marks.values())
print(student_marks.items())

# creating set
my_set = {'a','e','i','o','u','a','a','i'}
print(my_set)

# set automatically removes duplicates and unorderd

# try to change set values
my_set[4] = 's'
print(my_set)

# set dodn't have any index so we can't change particular index values we can do only add and remove functions

# creating two sets, union and intersection
set1 = {1, 3, 5, 7, 9}
set2 = {2, 3, 5, 8, 10}

print("union set: ", set1.union(set2))
print("intersection set: ", set1.intersection(set2))

# getting input value from users
score = int(input("Enter score from 0 to 10: "))
if score < 0 or score > 10:
  print("Invalid score please enter values from 0 to 10")
else:
    if score > 7:
      print("Above Average")
      print("Great job! keep up the excellent performance")
    elif 4 <= score <= 7:
      print("Average")
      print("Good effort! There is room for improvement")
    else:
      if score < 4:
        print("Below average")
        print("Need to improve your performance! practice consistently")