# -*- coding: utf-8 -*-
"""Assignment 1 python - mathan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n9IoQVOSFYRV0B94RunzrRJJI3CYdxe6
"""

# String Concatenation

string_1 = "Hello "
string_2 = input("Enter Your name: ")
string_3 = ", welcome to Python programming"
result = string_1 + string_2 + string_3
print(result)

# first character of the string
result[0]

# last character of the string
result[-1]

# first 5 character of the string
result[:5]

# last 11 character of the string
result[-11:]

# reverse order
result[::-1]

# printing python
result[23:29]

# string method
strM = "Python beginner tutorial"
print(strM)

# upper

print(strM.upper())

# lower
print(strM.lower())

# capitalize
print(strM.capitalize())

# count t value
result_t= strM.count('t')
print(result_t)

# replace
replace_strM = strM.replace("Python", "Machine Learning")
print(replace_strM)

# tuple creation
t1 = (10, 20, 30)
t2 = (40, 50, 60)

# concatenate
t_combine = t1 + t2
print(t_combine)

# repeat
t_repeat = t_combine * 3
print(t_repeat)

# element access 3rd element
t_combine[2]

# element access 1 to 3 elements
t_combine[:3]

# element access last 3 elements
t_combine[-3:]

