# -*- coding: utf-8 -*-
"""Customer Support Ticket Analyser - Module End Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oB6lG6ETRMNO-ros1gCnycPlbEGHnpqD
"""

## Raw data

ticket_data = {    'Ticket_No': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Customer_Name': [ 'Ravi', 'Meera', 'Sam', 'Anu', 'Rakesh', 'Divya', 'Arjun', 'Kiran', 'Leela', 'Nisha'
    ],
 'Issue_Description': [
        ' Internet not working!!! ', 'slow response, very poor service ',
        'GREAT support! issue resolved.',' okay... need help ', 'not BAD but slow', 'Excellent guidance, Very Helpful!', 'good support and good behaviour!', 'Poor handling of technical issue', 'Satisfied. Could be better.',  'Good service... quick response.'
    ],
  'Priority': ['High', 'Low', 'High', 'Medium', 'Low', 'High', 'Medium', 'High', 'Low', 'Medium']}
print(ticket_data)

## Printing data with reading format

print("Customer support tickets:\n")

for i in range(len(ticket_data['Ticket_No'])):
  print(f"Ticket No: {ticket_data['Ticket_No'][i]}")
  print(f"Customer Name: {ticket_data['Customer_Name'][i]}")
  print(f"Issue Description: {ticket_data['Issue_Description'][i]}")
  print(f"Priority: {ticket_data['Priority'][i]}")
  print(" \n")

## Adding new ticket

num_tickets = int(input("How many tickets do you want to add? "))

current_ticket_no = ticket_data['Ticket_No'][-1]

for i in range(num_tickets):
  current_ticket_no += 1
  print(f" Enter details for ticket {current_ticket_no}")

  name = input("Customer Name: ")
  issue = input('Issue Description: ')

  while True:
    priority = input("Priority (High, Medium, or Low): ").capitalize()
    if priority in ['High', 'Medium', 'Low']:
      break
    else:
      print(f"Invalid priority! Please enter High, Medium, or Low.")

ticket_data['Ticket_No'].append(current_ticket_no)
ticket_data['Customer_Name'].append(name)
ticket_data['Issue_Description'].append(issue)
ticket_data['Priority'].append(priority)

print("\n Ticket created successfully!")

## Cleaning data

cleaned_data = []

for issue in ticket_data['Issue_Description']:

  issue = issue.lower()

  issue = issue.replace(".", "")
  issue = issue.replace(",", "")
  issue = issue.replace("!", "")
  issue = issue.replace("?", "")
  issue = issue.replace("-", "")

  issue = " ".join(issue.split())

  issue = issue.strip()

  issue = issue.replace("ok", "okay")

  cleaned_data.append(issue)

ticket_data['Issue_Description'] = cleaned_data

print(ticket_data)

## Keyword-Based Issue Insights

def count_tickets_with_word(word):
  count = 0
  word = word.lower()

  for issue in ticket_data['Issue_Description']:
    if word in issue.lower():
      count += 1
  return count

print("Tickets containing 'poor': ", count_tickets_with_word('Poor'))
print("Tickets containing 'good': ", count_tickets_with_word('good'))
print("Tickets containing 'slow': ", count_tickets_with_word('slow'))
print("Tickets containing 'excellent': ", count_tickets_with_word('excellent'))

## Final cleaned data

print(f"Cleaned ticket data \n")

for i in range(len(ticket_data['Ticket_No'])):
  print(f"Ticket No: ", ticket_data['Ticket_No'][i])
  print(f"Customer Name: ", ticket_data['Customer_Name'][i])
  print(f"Issue description: ", ticket_data['Issue_Description'][i])
  print(f"Priority: ", ticket_data['Priority'][i])
  print(f"\n")

## Priority based counts

high = ticket_data['Priority'].count('High')
medium = ticket_data['Priority'].count('Medium')
low = ticket_data['Priority'].count('Low')

print(f"High priority count: ", high)
print(f"Medium priority count: ", medium)
print(f"Low priority count: ", low)

## Finding longest ticket description

max_words = 0
max_index = 0

for i, issue in enumerate(ticket_data['Issue_Description']):
  word_count = len(issue.split())

  if word_count > max_words:
    max_words = word_count
    max_index = i

print(f"Ticket with longest issue content")
print(f"Ticket Number: ", ticket_data['Ticket_No'][max_index])
print(f"Customer name: ", ticket_data['Customer_Name'][max_index])
print(f"Cleaned issue text: ", ticket_data['Issue_Description'][max_index])
print(f"word count: ", max_words)

## Unique words used

unique_words = set()

for issue in ticket_data['Issue_Description']:
  words = issue.split()
  unique_words.update(words)

sorted_words = sorted(unique_words)

print("\nUnique words analysis: ")
print("Total Unique Words:", len(sorted_words))
print("Word List:")
print(sorted_words)

"""## Action Summary

We processed customer support ticket data, performing the following key actions:

1.  **Initial Data Setup:** A dictionary named `ticket_data` was created, containing details such as ticket numbers, customer names, issue descriptions, and priorities.

2.  **Data Display:** The initial and cleaned ticket data were displayed in a readable format, showing individual ticket details.

3.  **Ticket Addition:** Functionality was implemented to add a new ticket interactively, prompting for customer name, issue description, and priority. One new ticket was added during execution.

4.  **Issue Description Cleaning:** The `Issue_Description` field for all tickets underwent a cleaning process. This included converting text to lowercase, removing punctuation (periods, commas, exclamation marks, question marks, hyphens), standardizing whitespace, and replacing "ok" with "okay".

5.  **Keyword Analysis:** A function was defined to count tickets containing specific keywords (e.g., 'poor', 'good', 'slow', 'excellent') within their issue descriptions. The counts for these keywords were then displayed.

6.  **Priority Distribution Analysis:** The total counts for 'High', 'Medium', and 'Low' priority tickets were calculated and presented.

7.  **Longest Issue Identification:** The ticket with the longest issue description (based on word count) was identified, and its details (Ticket Number, Customer Name, Cleaned Issue Text, and Word Count) were printed.

8.  **Unique Words Analysis:** All unique words from the cleaned issue descriptions were extracted, sorted alphabetically, and displayed along with the total count of unique words.
"""